# https://github.com/deepmap/oapi-codegen#using-oapi-codegen

output:
  pkg/distributed/schema/client.gen.go
package: schema
generate:
  - types
  - client
  - server
  
# import-mapping:
#   ./swagger.yml: github.com/deepmap/oapi-codegen/internal/test/externalref/packageA
#   ./packageB/spec.yaml: github.com/deepmap/oapi-codegen/internal/test/externalref/packageB
